---
abstract: 'Tie::Array::QueueExpire Is a tie ARRAY over a TokyoCabinet::BDB database with expiration function'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tie-Array-QueueExpire
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: '0'
  Time::HiRes: '0'
version: '1.04'
