--- #YAML:1.0
name:               Tie-Array-QueueExpire
version:            1.01
abstract:           Tie::Array::QueueExpire Is a tie ARRAY over a TokyoCabinet::BDB database with expiration function
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    TokyoCabinet:  Time::HiRes
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
