--- #YAML:1.0
name:                Tie-Array-QueueExpire
version:             0.55
abstract:            Tie::Array::QueueExpire Is a tie ARRAY over a TokyoCabinet::BDB database with expiration function
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    TokyoCabinet:                  Time::HiRes
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
